development:
  adapter: postgresql
  encoding: unicode
  database: leschnerguitars_dev
  pool: 5
  username: nellyduclos
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: leschnerguitars_test
  pool: 5
  username: nellyduclos
  password:
